---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1mx63czkmwxk00w0f0nvlaydjla8mkmjftr2lus3k2ty46wfx9cqsnj9rvm"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1mx63czkmwxk00w0f0nvlaydjla8mkmjftr2lus3k2ty46wfx9cqsnj9rvm"
stores:
  yaml:
    indent: 2
