# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kigoQkCtRlzbra7CErhSpYwMVjxAkLNP8X7t0FL6VCNuCutQW54Lkun3+vkJ7Gk/1XB76h/lu3eMdYM8JXRXni2nLiIPetZAfng1kp16EbJ2C9XGlRV5EVztgl/xfVMK/W0BKN9yZeHodCJncCwscbk4zgxFMi1RrV/8hgoiMXdzh4Vhf/F1Fi1FT5vqsvXeJ+0CrBEKvl0iHcIZzhQ1K4Mz+tE/6S+Br7EnInn2Y5nN79Gp,iv:PO5zB90m6iX5FrhzGBCKjHuf/cR84Lf6blKLFeRCQKU=,tag:RhwhKgvKiZRGtRtQUcNbgQ==,type:str]
sops:
  age:
    - recipient: age1mx63czkmwxk00w0f0nvlaydjla8mkmjftr2lus3k2ty46wfx9cqsnj9rvm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZlRQeEx6UElyUVRVNFk0
        N1RiZWZwZHhpdDVkMUF5T2pmbGZHU0l1QTNvClJobk9rbG5uM0pnN2taQmx1c05W
        WVMxVFc2T0VWbVVFWHZKaHRvMWQzQWMKLS0tIElJTWU4NlltU1VQT2NHU2VaajU4
        bG9hYXBueXVTdndNWTREaXZ3RHE4dFkKUa7iHLLpeurDOp5o7+SuO/gAbJlH0irk
        OzRckMlRRbqXiCV/pQLVhyoJy+6IpY/rAtfeoTkuAh8BAGiRfGfqgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T18:25:12Z"
  mac: ENC[AES256_GCM,data:dBkr8CY6Nx8Pr2tVm7JJqCyE1UFPglo76Or0UQg6cODb9DIirqgcdlUk8QK1nY8Sz4lCv/kMaYAiVZht63w10eiVECWoKMMyEYFj4PMs5PrAoF9wQuB6ekUBTzogKV5ylcQzvENHr68fG52h8YGqGruX3iCzXiIobtSd1h5OYzw=,iv:7dSd2ZVc83yXRGB5Bsp9GsDMpgEqils87yOVKlfjaR8=,tag:IYBHmgl5e3VBZMa2GndQoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
