apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:g44nFzgoE9O1mg==,iv:wppnZQz2M9iKiDDZTFDsyCZhohHC3Diftzu38OYalu0=,tag:8ffpHLYeQQ32R5Qgb94AXw==,type:str]
sops:
  age:
    - recipient: age1mx63czkmwxk00w0f0nvlaydjla8mkmjftr2lus3k2ty46wfx9cqsnj9rvm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndGNjK0FCckJVQzVBM08w
        VDNYOE5RVFhLZEVNbFNZTmZsY3N5QWpGU1RjCm9rM0NyeEFCbXdMdUROL01oNnNR
        OUNjUlVSMVNDRnM0WnplSDE3RDh0dTgKLS0tIFJya0o3alJBN1YrbmpUZDE4YTlF
        QTNMcm1UVitxMCs2Z1JmZWUrWmhnckUKK6+wlj9nHVHOJfGRSlMwi3LgO2POg8iX
        aLoL58O5O/plpUC5+bpBMjsfiVPU3wlpGYPTGny0yxbDrq+F6oa3Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T18:25:11Z"
  mac: ENC[AES256_GCM,data:t6AT/9edYFWJQU0CuQO05Q4VPOFy4e62DHCaP97KvFQU5RCCJC3uSYwnvkm2yMCD0p5RE7MDCrlGpS8NcNLrSh11pT8oYN4gYKz26maVNNeXOpF1MpZdlW+wCVnXJwWSH3S8q9GE6ntFcRbj2duekl0XRND0KCUh5sdENj2dG6U=,iv:ODV4HlbUHFIuFpEGw2FMQOhmD56glR5xlUF4BUfxbE4=,tag:D47oUUFxqoHU6qo3iDXBzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
